// Date: 14.12.2013 12:23:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package npe.arcade.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelArcadeTechne extends ModelBase
{
    //fields
    ModelRenderer Base;

    public ModelArcadeTechne()
    {
        textureWidth = 512;
        textureHeight = 512;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(-8F, -8F, -8F, 16, 16, 16);
        Base.setRotationPoint(0F, 16F, 0F);
        Base.setTextureSize(512, 512);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);

        // screen in seperate model
        //        Screen = new ModelRenderer(this, 0, 32);
        //        Screen.addBox(-7F, -10F, 0F, 14, 10, 1);
        //        Screen.setRotationPoint(0F, 8F, -2.033333F);
        //        Screen.setTextureSize(512, 512);
        //        Screen.mirror = true;
        //        setRotation(Screen, -0.5235988F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
